version: '3.4'

services:
  nginx:
    image: nginx:latest@sha256:1f9c00b4c95ef931afa097823d902e7602aebc3ec5532e907e066978075ca3e0
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/nginx/nginx.api.conf:/etc/nginx/conf.d/api.conf
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: default.Dockerfile
    container_name: api
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - PG_USER_NAME=pguser
      - PG_PASS=pguser
      - PG_DB=db
      - PG_SCHEMA=public
      - PG_HOST=postgres
      - PG_PORT=5432
    ports:
      - 9229:9229
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:latest@sha256:e033c99282a81622b1eed36b735034e10d633a34cca3387f6142381770cfbcc8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: db
      TZ: "America/Sao_Paulo"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
volumes:
  postgres-data:
